### ISSUE TITLE
bug with MultiSelects in the filter's card

### ISSUE THREAD

**Issue by rosamarsky** [dcasia/nova-dashboard#81]
`overflow: hidden` hides multisect dropdowns.

<img width="685" alt="image" src="https://github.com/dcasia/nova-dashboard/assets/15215861/1f7c598b-e591-405b-8d7d-96e6e5e7d873">

Solve - add it to styles:
```css
.nova-dashboard-filter *[data-collapse="expanding"] {
    overflow: visible !important;
}
```
